### ISSUE TITLE
Share Dockerfile

### ISSUE THREAD

**Issue by zackkitzmiller** [gato/roach-on-pi#1]
Is it possible you could share the Dockerfile for this repo? There have been a couple of CRDB Version Revs since you posted this, and I'd like to keep up to date if possible.

**Comment by zackkitzmiller** [comment]
I am an idiot.

**Comment by gato** [comment]
Hi @zackkitzmiller, Don't be that hard on yourself. :) 

I know CRDB released version 20.2 yesterday, I was planning to update Dockerfile and also update Dockerhub image in the next couple of days. 

I wasn't aware that people were actually using this image. 
Will try to update it asap and try to keep up with the new versions.

Cheers.
Marcelo

**Comment by zackkitzmiller** [comment]
Haha, I am :). Not for anything serious, I'm just doing hobbiest stuff with it. I'm currently building 20.2.0 right now, and am publishing to Dockerhub.

**Comment by gato** [comment]
FYI: I've already updated repo and dockerhub image to CockroachDB 20.2.0 // CC: @zackkitzmiller
